set -em

LOGS_DIR=logs
CONTRACT_ADDRESS=`cat $LOGS_DIR/contractAddresses.log | sed -n "s/DOMAINREGISTAR_CONTRACT_ADDRESS=\([^']\+\).*/\1/p"`
cd backend
CONTRACT_ADDRESS=$CONTRACT_ADDRESS ABI_FILEPATH=$ABI_FILEPATH node .
